services:
  mediawiki:
    build:
      context: .
      dockerfile: Dockerfile-mediawiki
      args:
        MW_INSTALL_EXTENSIONS: ${MW_INSTALL_EXTENSIONS:-}
        MW_INSTALL_SKINS: ${MW_INSTALL_SKINS:-}
    image: mmediawiki-custom
    pull_policy: never
    env_file:
      - .env.ci

  memcachephp:
    build:
      context: .
      dockerfile: Dockerfile-memcachephp
    image: memcachephp
    pull_policy: never
