services:
  mediawiki:
    build:
      context: .
      dockerfile: Dockerfile-mediawiki
      args:
        MW_EXTENSIONS: ${MW_EXTENSIONS:-}
        MW_SKINS: ${MW_SKINS:-}
    image: mediawiki:latest
    pull_policy: never

  memcachephp:
    build:
      context: .
      dockerfile: Dockerfile-memcachephp
    image: memcachephp:latest
    pull_policy: never
