services:
  mediawiki:
    build:
      context: .
      dockerfile: Dockerfile-mediawiki
      args:
        MW_EXTENSIONS: ${MW_EXTENSIONS:-}
        MW_SKINS: ${MW_SKINS:-}
    image: mmediawiki-custom
    pull_policy: never
    volumes: []

  memcachephp:
    build:
      context: .
      dockerfile: Dockerfile-memcachephp
    image: memcachephp
    pull_policy: never
