services:
  mediawiki:
    build:
      context: .
      dockerfile: Dockerfile-mediawiki
      args:
        MW_EXTENSIONS: ${MW_EXTENSIONS:-}
        MW_SKINS: ${MW_SKINS:-}
    image: mmediawiki-custom
    pull_policy: never
    environment:
      MW_CONFIG_FILE: ${MW_CONFIG_FILE:-/var/www/html/LocalSettings.php}
    env_file:
      - .env.ci


  memcachephp:
    build:
      context: .
      dockerfile: Dockerfile-memcachephp
    image: memcachephp
    pull_policy: never
